### PR TITLE
Add totalWaiters to PoolStats

### PR DESCRIPTION
**Pull request by steve-chavez**
Hello @avanov ,

As mentioned in https://github.com/bos/pool/pull/42#issuecomment-1015982190, I'd like to limit the waiter queue to do backpressure. So I've added `totalWaiters` to `PoolStats`.

Related: https://github.com/PostgREST/postgrest/issues/2042#issuecomment-1021838477

LMWYT, thanks!

### CODE REVIEW

**Comment by avanov** [comment]
This looks good and useful semantically. What I'm not sure of is whether the length of the queue should be calculated here or inside `WaiterQueue` module. Logically it's a property of the queue entity that could be read from it, but never modified directly.

**Comment by steve-chavez** [comment]
@avanov Thanks for the review. I did it like this because I also plan to add `maxWaiters` and I think that wouldn't fit inside the `WaiterQueue` module. Seemed more consistent to have them both outside.

**Comment by avanov** [comment]
@steve-chavez yeah I get that from the linked discussion, though aren't they two different concepts? One has to do with a "peekable" stat value (property of the queue), another has to do with utilising all available underlying stats for higher level interface of back-pressuring (back-pressuring being a property of the queue). For instance, the following sequence:
```
removeSelf <- push waiters var
modifyTVar_ waitersSizeVar (+ 1)
```
it assumes that push always leads to (+1) for the stat value, and that `pop` results in `(subtract 1)`.

**Comment by steve-chavez** [comment]
@avanov Sorry for the late reply here. Since the newest **hasql-pool** doesn't use **resource-pool**([ref](https://github.com/nikita-volkov/hasql-pool/issues/14)), I no longer need this change(we're transitioning to the newest hasql-pool https://github.com/PostgREST/postgrest/pull/2391).

**Pull request closed without merging**
